server:
  port: 8080
  max_memory: 32000000 # 32MB
  max_file_size: 100000000 # 100MB
  storage:
    path: ./data/storage
  timeout:
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 60
    max_header_bytes: 1024
    read_header_timeout: 10
  
  upload:
    max_files_per_request: 50
    max_total_size_per_request: 524288000 # 500MB in bytes
    allow_partial_success: true        
    enable_batch_processing: true      
    batch_size: 10          
    max_concurrent_uploads: 3
    streaming_threshold: 10485760 # 10MB in bytes
    validate_before_upload: true
    enable_progress_tracking: false
    cleanup_on_failure: false    
    rate_limit_per_minute: 100

database:
  driver: sqlite3
  dsn: ./data/cloudlet.db
  max_conn: 10